# Redfin Market Data - Zip Code

## Overview
| Detail Tag            | Information                                                                                        |
|-----------------------|----------------------------------------------------------------------------------------------------|
| Originally Created By | Ariel Herrera arielherrera@analyticsariel.com |
| External References   | API |
| Input Datasets        | Source name |
| Output Datasets       | Source name |
| Input Data Source     | Pandas DataFrame |
| Output Data Source    | Pandas DataFrame |

## History
| Date         | Developed By  | Reason                                                |
|--------------|---------------|-------------------------------------------------------|
| 1st Jun 2021 | Ariel Herrera | Create notebook. |

## Getting Started
1. Copy this notebook -> File -> Save a Copy in Drive
2. Directions

## Useful Resources
- [Google Colab Cheat Sheet](https://towardsdatascience.com/cheat-sheet-for-google-colab-63853778c093)

## <font color="blue">Install Packages</font>

## <font color="blue">Imports</font>

In [1]:
from google.colab import drive, files # specific to Google Colab
from datetime import datetime
import pandas as pd
import time
import warnings

pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

## <font color="blue">Functions</font>

## <font color="blue">Locals & Constants</font>

## <font color="blue">Data</font>

In [2]:
# url link from - https://www.redfin.com/news/data-center/
url = 'https://redfin-public-data.s3.us-west-2.amazonaws.com/redfin_market_tracker/zip_code_market_tracker.tsv000.gz'

# start time to read file
startTime = time.time()
df = pd.read_csv(url, compression='gzip', sep='\t', on_bad_lines='skip')
# end time 
executionTime = (time.time() - startTime)
print('Execution time in minutes: ' + str(round(executionTime / 60, 2)))
print('Num of rows:', len(df))
print('Num of cols:', len(df.columns))
df.head()

Execution time in minutes: 2.62
Num of rows: 6020132
Num of cols: 58

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2021-12-01,2022-02-28,90,zip code,2,39641,f,Zip Code: 95448,NaN,California,CA,Single Family Residential,6,945500.0,0.027717,-0.113247,1100000.0,-0.056846,0.004566,622.583140,0.048797,0.077815,718.237407,0.112958,0.240122,44.0,-0.200000,0.000000,6.0,-0.40000,-0.400000,33.0,0.178571,-0.440678,36.0,0.200000,-0.400000,NaN,NaN,NaN,78.0,1.0,18.5,1.003355,0.009444,0.024138,0.340909,-0.022727,0.159091,NaN,NaN,NaN,0.333333,0.133333,0.133333,"Santa Rosa, CA",42220,2022-07-10 14:38:35
1,2017-03-01,2017-05-31,90,zip code,2,30050,f,Zip Code: 70426,NaN,Louisiana,LA,Single Family Residential,6,148497.5,0.000000,NaN,76005.0,-0.074351,NaN,52.615660,0.000000,NaN,46.810238,-0.196424,NaN,2.0,0.000000,NaN,NaN,NaN,NaN,2.0,-0.600000,NaN,10.0,0.000000,NaN,NaN,NaN,NaN,1446.5,0.0,NaN,0.960870,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Bogalusa, LA",14220,2022-07-10 14:38:35
2,2014-03-01,2014-05-31,90,zip code,2,18470,f,Zip Code: 44072,NaN,Ohio,OH,Single Family Residential,6,167200.0,-0.071111,-0.375653,439750.0,0.355371,0.332576,81.007752,0.062296,-0.284186,130.902413,0.164418,0.124927,13.0,0.181818,-0.133333,1.0,-0.80000,-0.666667,26.0,0.083333,0.083333,46.0,0.210526,0.069767,NaN,NaN,NaN,75.0,-11.0,-28.0,0.968193,-0.002355,0.029987,0.076923,-0.013986,0.010256,NaN,NaN,NaN,0.000000,0.000000,0.000000,"Cleveland, OH",17460,2022-07-10 14:38:35
3,2015-09-01,2015-11-30,90,zip code,2,31066,f,Zip Code: 72501,NaN,Arkansas,AR,All Residential,-1,61000.0,-0.188285,-0.065134,42543.5,-0.058501,-0.278924,26.967286,-0.255338,-0.246233,26.623309,-0.145919,-0.268536,1.0,-0.500000,-0.500000,NaN,NaN,NaN,4.0,0.333333,3.000000,5.0,0.000000,1.500000,NaN,NaN,NaN,200.0,105.5,82.0,0.898380,-0.127108,-0.087150,0.000000,-1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,"Batesville, AR",12900,2022-07-10 14:38:35
4,2018-09-01,2018-11-30,90,zip code,2,11034,f,Zip Code: 27615,NaN,North Carolina,NC,All Residential,-1,300000.0,-0.009083,0.048951,299950.0,0.034667,0.016780,147.435317,0.011395,0.090195,146.152300,-0.019559,0.019538,178.0,-0.144231,-0.082474,43.0,-0.31746,-0.122449,172.0,-0.135678,-0.039106,146.0,-0.013514,-0.081761,NaN,NaN,NaN,51.0,2.0,1.0,0.993882,-0.002792,0.008813,0.348315,-0.021878,0.054500,NaN,NaN,NaN,0.209302,0.034699,0.066445,"Raleigh, NC",39580,2022-07-10 14:38:35

## <font color="blue">Transformations</font>

In [3]:
# filter on state code
state_code = 'CA'
df_filter = df.loc[df['state_code'] == state_code]
print('Num of rows:', len(df_filter))
df_filter.head()

Num of rows: 613152

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2021-12-01,2022-02-28,90,zip code,2,39641,f,Zip Code: 95448,NaN,California,CA,Single Family Residential,6,945500.0,0.027717,-0.113247,1100000.0,-0.056846,0.004566,622.583140,0.048797,0.077815,718.237407,0.112958,0.240122,44.0,-0.200000,0.000000,6.0,-0.400000,-0.400000,33.0,0.178571,-0.440678,36.0,0.200000,-0.400000,NaN,NaN,NaN,78.0,1.0,18.5,1.003355,0.009444,0.024138,0.340909,-0.022727,0.159091,NaN,NaN,NaN,0.333333,0.133333,0.133333,"Santa Rosa, CA",42220,2022-07-10 14:38:35
10,2018-06-01,2018-08-31,90,zip code,2,39533,f,Zip Code: 95315,NaN,California,CA,All Residential,-1,249000.0,0.018405,0.016327,272500.0,-0.009091,-0.009091,190.476190,-0.064684,0.100190,182.319850,-0.028813,-0.002876,21.0,0.166667,0.105263,5.0,-0.444444,-0.166667,18.0,-0.280000,-0.280000,14.0,-0.176471,-0.333333,NaN,NaN,NaN,42.0,7.0,15.0,0.961265,-0.008603,-0.022677,0.190476,-0.031746,-0.020050,NaN,NaN,NaN,0.600000,0.488889,-0.066667,"Merced, CA",32900,2022-07-10 14:38:35
13,2015-03-01,2015-05-31,90,zip code,2,39312,f,Zip Code: 94929,NaN,California,CA,All Residential,-1,699000.0,0.168896,0.370588,959750.0,0.175084,0.281375,431.861804,0.029824,0.122841,411.225948,-0.153590,-0.132740,9.0,0.000000,2.000000,NaN,NaN,NaN,2.0,-0.500000,-0.714286,2.0,-0.333333,-0.800000,NaN,NaN,NaN,101.0,56.0,-105.0,0.926678,0.010285,-0.001785,0.111111,0.000000,0.111111,NaN,NaN,NaN,NaN,NaN,NaN,"San Rafael, CA",42034,2022-07-10 14:38:35
24,2021-06-01,2021-08-31,90,zip code,2,39402,f,Zip Code: 95065,NaN,California,CA,Single Family Residential,6,1410000.0,-0.090323,0.207709,1197500.0,-0.078137,0.197501,725.294651,0.000000,0.023080,672.867935,0.026758,0.111455,25.0,0.086957,0.388889,5.0,-0.375000,0.250000,20.0,-0.285714,-0.200000,14.0,-0.066667,0.166667,NaN,NaN,NaN,29.0,-0.5,-1.0,1.065432,-0.018871,0.040718,0.720000,0.067826,0.108889,NaN,NaN,NaN,0.600000,0.350000,-0.150000,"Santa Cruz, CA",42100,2022-07-10 14:38:35
42,2018-05-01,2018-07-31,90,zip code,2,39299,f,Zip Code: 94904,NaN,California,CA,All Residential,-1,1835000.0,-0.023936,0.054598,1774000.0,-0.132942,-0.000563,824.800910,0.032774,0.015727,786.982332,-0.013087,0.052233,49.0,0.113636,0.256410,12.0,-0.368421,-0.076923,62.0,-0.114286,0.771429,38.0,-0.050000,1.000000,NaN,NaN,NaN,27.0,0.0,12.0,1.020695,-0.006168,-0.027929,0.551020,-0.062616,-0.115646,NaN,NaN,NaN,0.166667,-0.201754,-0.141026,"San Rafael, CA",42034,2022-07-10 14:38:35

In [ ]:
df_filter.describe()

### Sample Dataset

In [4]:
"""
PROBLEM - Data takes a long time to load in Tableau
RESOLUTION - Sample a subset of zip codes
"""
# get zip code county data
geo_data_url = 'https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv'
df_geo = pd.read_csv(geo_data_url)
print('Num of rows:', len(df_geo))
print('Num of columns:', len(df_geo.columns))
df_geo.head()

Num of rows: 33103
Num of columns: 6

   state_fips    state state_abbr zipcode      county        city
0           1  Alabama         AL   35004   St. Clair       Acmar
1           1  Alabama         AL   35005   Jefferson  Adamsville
2           1  Alabama         AL   35006   Jefferson       Adger
3           1  Alabama         AL   35007      Shelby    Keystone
4           1  Alabama         AL   35010  Tallapoosa    New site

In [5]:
# filter on counties
df_geo_county = df_geo.loc[(df_geo['state_abbr'] == 'CA') &
                           (df_geo['county'].isin(['Los Angeles', 'Orange', 'San Diego']))]
# create feature to check if zip code is valid
df_geo_county['valid_zip_code'] = df_geo_county.apply(lambda x: x['zipcode'].isnumeric(), axis=1)
print('Dataset:')
print(df_geo_county.groupby(['valid_zip_code', 'county'])['zipcode'].count())
print(' ')
print('Invalid zip codes:', df_geo_county.loc[df_geo_county['valid_zip_code'] == False]['zipcode'].unique())

Dataset:
valid_zip_code  county
False           Los Angeles     14
                Orange           5
                San Diego        5
True            Los Angeles    275
                Orange          84
                San Diego       95
Name: zipcode, dtype: int64

Invalid zip codes: ['900HH' '902HH' '904HH' '906HH' '907HH' '907XX' '908HH' '910HH' '910XX'
 '913HH' '913XX' '917HH' '917XX' '919HH' '919XX' '920HH' '920XX' '921HH'
 '926HH' '926XX' '927HH' '928HH' '928XX' '935HH']

In [6]:
# filter on only valid zip codes
df_geo_county_valid = df_geo_county.loc[df_geo_county['valid_zip_code'] == True]
print('Num of VALID zip codes:', len(df_geo_county_valid))
df_geo_county_valid.head(1)

Num of VALID zip codes: 454

,state_fips,state,state_abbr,zipcode,county,city,valid_zip_code
1903,6,California,CA,90001,Los Angeles,Los angeles,True

In [7]:
# get zip code from region field
df_filter['zipcode'] = df_filter.apply(lambda x: x['region'].split(':')[1].strip(), axis=1)
# merge market data and geo zip codes
df_merge = pd.merge(
    df_filter,
    df_geo_county_valid[['zipcode', 'city', 'county']],
    how='inner', # only return zip codes from BOTH tables
    on=['zipcode'] # field to join on
)
print('Num of rows:', len(df_merge))
df_merge.head()

Num of rows: 231327

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city_x,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated,zipcode,city_y,county
0,2013-10-01,2013-12-31,90,zip code,2,37584,f,Zip Code: 90274,NaN,California,CA,Single Family Residential,6,1471500.0,-0.005743,0.066304,1629000.0,0.069248,0.034286,553.731920,-0.012900,0.116409,636.669482,0.042993,0.181242,68.0,-0.042254,-0.068493,21.0,0.400000,0.105263,48.0,-0.314286,-0.186441,30.0,-0.302326,-0.117647,NaN,NaN,NaN,29.0,8.0,-2.0,0.965912,-0.009285,0.002455,0.147059,-0.106462,0.037470,NaN,NaN,NaN,0.238095,-0.228571,-0.340852,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles
1,2016-03-01,2016-05-31,90,zip code,2,37584,f,Zip Code: 90274,NaN,California,CA,Single Family Residential,6,1534000.0,-0.041250,-0.115850,1880000.0,-0.004237,0.118049,641.897588,-0.015118,0.034731,666.666364,-0.002277,0.027847,94.0,0.160494,0.160494,31.0,0.068966,0.033333,127.0,-0.045113,0.076271,114.0,0.027027,0.239130,NaN,NaN,NaN,51.5,-3.5,-5.5,0.988640,0.002122,0.021780,0.265957,0.006698,0.080772,NaN,NaN,NaN,0.161290,-0.114572,-0.238710,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles
2,2019-10-01,2019-12-31,90,zip code,2,37584,f,Zip Code: 90274,NaN,California,CA,All Residential,-1,1585000.0,0.000789,-0.067647,1650000.0,0.000000,-0.131122,667.177914,0.008024,0.050095,691.025641,-0.031501,-0.027755,91.0,0.011111,0.263889,16.0,-0.448276,0.000000,71.0,-0.310680,-0.134146,99.0,-0.175000,0.000000,NaN,NaN,NaN,70.0,7.5,11.0,0.984427,0.002454,0.011177,0.285714,0.041270,0.105159,NaN,NaN,NaN,0.312500,0.002155,0.062500,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles
3,2015-07-01,2015-09-30,90,zip code,2,37584,f,Zip Code: 90274,NaN,California,CA,Single Family Residential,6,1840000.0,0.023644,0.095890,1920000.0,-0.007495,0.129412,660.140236,0.017786,0.055018,698.912802,0.031561,0.047932,90.0,-0.134615,0.000000,18.0,-0.333333,0.200000,103.0,-0.169355,0.072917,105.0,0.039604,0.000000,NaN,NaN,NaN,41.0,2.0,23.0,0.986137,-0.001441,0.010764,0.277778,-0.020299,0.066667,NaN,NaN,NaN,0.166667,0.018519,-0.300000,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles
4,2019-11-01,2020-01-31,90,zip code,2,37584,f,Zip Code: 90274,NaN,California,CA,Condo/Co-op,3,512750.0,0.035859,0.523774,719900.0,0.044848,1.027887,590.903623,0.032906,0.008087,604.940150,0.051862,0.122973,12.0,0.090909,0.714286,3.0,0.500000,-0.250000,12.0,0.090909,0.333333,10.0,-0.090909,1.500000,NaN,NaN,NaN,46.0,12.5,16.0,1.001080,-0.005777,0.009649,0.333333,-0.030303,0.190476,NaN,NaN,NaN,0.333333,-0.166667,0.083333,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles

### View Bad Data from Redfin

In [8]:
# choose a specific zip code / property type and view MoM change
# TODO: Future auto loop through each MoM column and recalulate
df_merge.loc[(df_merge['zipcode'] == '33510') & 
             (df_merge['property_type'] == 'Single Family Residential')]\
  .sort_values(by=['period_begin']).tail(2)\
  [['period_begin', 'median_dom', 'median_dom_mom', 'median_dom_yoy']]

Empty DataFrame
Columns: [period_begin, median_dom, median_dom_mom, median_dom_yoy]
Index: []

In [9]:
# test to correct the error
df_test = df_merge.copy()
df_test['median_dom_mom_correction'] = df_test.sort_values(by=['period_begin'])['median_dom'].pct_change()
df_test.loc[(df_test['zipcode'] == '33510') & 
             (df_test['property_type'] == 'Single Family Residential')]\
  .sort_values(by=['period_begin']).tail(2)\
  [['period_begin', 'median_dom', 'median_dom_mom', 'median_dom_yoy', 'median_dom_mom_correction']]

Empty DataFrame
Columns: [period_begin, median_dom, median_dom_mom, median_dom_yoy, median_dom_mom_correction]
Index: []

### Add Features

In [10]:
# add features
df_features = df_merge.copy()
print('Max begin date:', df_features['period_begin'].max())
print('Max end date:', df_features['period_end'].max())
max_end_date = df_features['period_end'].max()

# 1) flag for most recent date
df_features['latest_period'] = df_features.apply(
    lambda x: True if x['period_end'] == max_end_date else False, axis=1)

# 2) remove Redfin city and keep Geo city
df_features = df_features.drop(columns=['city_x'])
df_features = df_features.rename(columns={'city_y': 'city'})

# 3) fix median days on market (bad data)
df_features['median_dom_mom'] = df_features.sort_values(by=['period_begin'])['median_dom'].pct_change()

# view first 5 rows
df_features.head()

Max begin date: 2022-04-01
Max end date: 2022-06-30

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated,zipcode,city,county,latest_period
0,2013-10-01,2013-12-31,90,zip code,2,37584,f,Zip Code: 90274,California,CA,Single Family Residential,6,1471500.0,-0.005743,0.066304,1629000.0,0.069248,0.034286,553.731920,-0.012900,0.116409,636.669482,0.042993,0.181242,68.0,-0.042254,-0.068493,21.0,0.400000,0.105263,48.0,-0.314286,-0.186441,30.0,-0.302326,-0.117647,NaN,NaN,NaN,29.0,-0.121212,-2.0,0.965912,-0.009285,0.002455,0.147059,-0.106462,0.037470,NaN,NaN,NaN,0.238095,-0.228571,-0.340852,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles,False
1,2016-03-01,2016-05-31,90,zip code,2,37584,f,Zip Code: 90274,California,CA,Single Family Residential,6,1534000.0,-0.041250,-0.115850,1880000.0,-0.004237,0.118049,641.897588,-0.015118,0.034731,666.666364,-0.002277,0.027847,94.0,0.160494,0.160494,31.0,0.068966,0.033333,127.0,-0.045113,0.076271,114.0,0.027027,0.239130,NaN,NaN,NaN,51.5,1.641026,-5.5,0.988640,0.002122,0.021780,0.265957,0.006698,0.080772,NaN,NaN,NaN,0.161290,-0.114572,-0.238710,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles,False
2,2019-10-01,2019-12-31,90,zip code,2,37584,f,Zip Code: 90274,California,CA,All Residential,-1,1585000.0,0.000789,-0.067647,1650000.0,0.000000,-0.131122,667.177914,0.008024,0.050095,691.025641,-0.031501,-0.027755,91.0,0.011111,0.263889,16.0,-0.448276,0.000000,71.0,-0.310680,-0.134146,99.0,-0.175000,0.000000,NaN,NaN,NaN,70.0,0.166667,11.0,0.984427,0.002454,0.011177,0.285714,0.041270,0.105159,NaN,NaN,NaN,0.312500,0.002155,0.062500,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles,False
3,2015-07-01,2015-09-30,90,zip code,2,37584,f,Zip Code: 90274,California,CA,Single Family Residential,6,1840000.0,0.023644,0.095890,1920000.0,-0.007495,0.129412,660.140236,0.017786,0.055018,698.912802,0.031561,0.047932,90.0,-0.134615,0.000000,18.0,-0.333333,0.200000,103.0,-0.169355,0.072917,105.0,0.039604,0.000000,NaN,NaN,NaN,41.0,1.050000,23.0,0.986137,-0.001441,0.010764,0.277778,-0.020299,0.066667,NaN,NaN,NaN,0.166667,0.018519,-0.300000,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles,False
4,2019-11-01,2020-01-31,90,zip code,2,37584,f,Zip Code: 90274,California,CA,Condo/Co-op,3,512750.0,0.035859,0.523774,719900.0,0.044848,1.027887,590.903623,0.032906,0.008087,604.940150,0.051862,0.122973,12.0,0.090909,0.714286,3.0,0.500000,-0.250000,12.0,0.090909,0.333333,10.0,-0.090909,1.500000,NaN,NaN,NaN,46.0,-0.515789,16.0,1.001080,-0.005777,0.009649,0.333333,-0.030303,0.190476,NaN,NaN,NaN,0.333333,-0.166667,0.083333,"Los Angeles, CA",31084,2022-07-10 14:38:35,90274,Palos verdes est,Los Angeles,False

## <font color="blue">Output</font>

In [11]:
date_str = datetime.today().strftime('%Y-%m')
print('Current year/month:', date_str)

Current year/month: 2022-07

In [13]:
# start time to download file
startTime = time.time()

# download file
df_features.to_csv('zip_realtor_{0}_{1}.csv'.format(state_code, date_str), index=False)
files.download('zip_realtor_{0}_{1}.csv'.format(state_code, date_str))

# end time 
executionTime = (time.time() - startTime)
print('Download time in minutes: ' + str(round(executionTime / 60, 2)))

Download time in minutes: 0.21

# End Notebook